# ====================================================
#       WEBSERV COMPLEX CONFIGURATION TEST
# ====================================================

# --- SERVER 1: The Main Website (Port 8080) ---
server {
    listen 8081;
    host 127.0.0.1;
    server_name localhost example.com;

    error_page 400 /errors/400.html;
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 405 /errors/405.html;
    error_page 413 /errors/413.html;
    error_page 500 /errors/500.html;
    error_page 501 /errors/501.html;
    error_page 502 /errors/502.html;
    error_page 503 /errors/503.html;
    error_page 504 /errors/504.html;

    client_max_body_size 1024;

    location / {
        root ./www/html/www/files;
        index index.html;
        autoindex off;
        allow_methods GET POST;
    }

    location /cgi-bin {
        root ./www/html/www/files; 
        autoindex on;
        allow_methods GET POST;
    }

    location /google {
        return 301 https://www.google.com;
    }

    location /signin {
        return 302 /login;
    }

    location /home {
        return 301 /;
    }

    location /images {
        alias ./www/assets/images;
        autoindex off;
        allow_methods GET;
    }
    
    location /uploads {
        root ./www/html/www/files;
        allow_methods GET POST DELETE; 
        autoindex on;
        client_max_body_size 500000000; 
    }
}

# ====================================================
#       WEBSERV COMPLEX CONFIGURATION TEST
# ====================================================

# --- SERVER 1: The Main Website (Port 8080) ---
server {
    listen 8080;
    host 127.0.0.1;
    server_name localhost example.com;

    error_page 400 /errors/400.html;
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 405 /errors/405.html;
    error_page 413 /errors/413.html;
    error_page 500 /errors/500.html;
    error_page 501 /errors/501.html;
    error_page 502 /errors/502.html;
    error_page 503 /errors/503.html;
    error_page 504 /errors/504.html;

    client_max_body_size 1024;

    location / {
        root ./www/html/www/files;
        index index.html;
        autoindex off;
        allow_methods GET POST;
    }

    location /cgi-bin {
        root ./www/html/www/files; 
        autoindex on;
        allow_methods GET POST;
    }

    location /google {
        return 301 https://www.google.com;
    }

    location /signin {
        return 302 /login;
    }

    location /home {
        return 301 /;
    }

    location /images {
        alias ./www/assets/images;
        autoindex off;
        allow_methods GET;
    }
    
    location /uploads {
        root ./www/html/www/files;
        allow_methods GET POST DELETE; 
        autoindex on;
        client_max_body_size 500000000; 
    }
}